#! /bin/sh

sxhkd &

# Pywal setup
. "${HOME}/.cache/wal/colors.sh"

# Start polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a polybar sticky=on

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
